import type {
  AgentTree,
  Agent,
  TrainingSession,
  Experiment,
  BriefingData,
  DiagnosticReport,
  RoutingData,
  WaveData,
  Deployment,
} from "@/types";

/* ── Agents ── */
const now = new Date().toISOString();

export const mockAgents: Agent[] = [
  {
    id: "orch-1",
    tree_id: "tree-1",
    name: "CustomerSupportOrchestrator",
    role: "orchestrator",
    model: "gemini-2.5-flash",
    instruction: "Route customer needs to specialists and preserve context.",
    description: "Primary support orchestrator",
    tools: ["route", "classify", "escalate"],
    parent_agent_id: null,
    score: 88,
    score_before: 62,
    is_shared: false,
    library_id: null,
    config_snapshot: "orchestrator_config_v1",
    created_at: now,
    updated_at: now,
  },
  {
    id: "auth-1",
    tree_id: "tree-1",
    name: "AuthAgent",
    role: "shared",
    model: "gemini-2.5-flash",
    instruction: "Authenticate customer before sensitive actions.",
    description: "Verifies identity",
    tools: ["verify_email", "verify_phone"],
    parent_agent_id: "orch-1",
    score: 91,
    score_before: 74,
    is_shared: true,
    library_id: "auth-agent-v2",
    config_snapshot: "AuthAgent_config_v1",
    created_at: now,
    updated_at: now,
  },
  {
    id: "billing-1",
    tree_id: "tree-1",
    name: "BillingAgent",
    role: "specialist",
    model: "gemini-2.5-flash",
    instruction: "Handles billing and disputes.",
    description: "Handles billing and disputes",
    tools: ["lookup_invoice", "charge_dispute"],
    parent_agent_id: "orch-1",
    score: 85,
    score_before: 58,
    is_shared: false,
    library_id: null,
    config_snapshot: "BillingAgent_config_v1",
    created_at: now,
    updated_at: now,
  },
  {
    id: "refund-1",
    tree_id: "tree-1",
    name: "RefundAgent",
    role: "specialist",
    model: "gemini-2.5-flash",
    instruction: "Handles returns and refunds.",
    description: "Handles returns and refunds",
    tools: ["lookup_order", "issue_refund"],
    parent_agent_id: "orch-1",
    score: 82,
    score_before: 55,
    is_shared: false,
    library_id: null,
    config_snapshot: "RefundAgent_config_v1",
    created_at: now,
    updated_at: now,
  },
  {
    id: "tech-1",
    tree_id: "tree-1",
    name: "TechSupportAgent",
    role: "specialist",
    model: "gemini-2.5-flash",
    instruction: "Handles technical issues.",
    description: "Handles technical issues",
    tools: ["search_kb", "reset_account"],
    parent_agent_id: "orch-1",
    score: 90,
    score_before: 67,
    is_shared: false,
    library_id: null,
    config_snapshot: "TechSupportAgent_config_v1",
    created_at: now,
    updated_at: now,
  },
  {
    id: "esc-1",
    tree_id: "tree-1",
    name: "EscalationAgent",
    role: "specialist",
    model: "gemini-2.5-flash",
    instruction: "Escalates critical issues.",
    description: "Escalates critical issues",
    tools: ["create_escalation_ticket"],
    parent_agent_id: "orch-1",
    score: 78,
    score_before: 60,
    is_shared: false,
    library_id: null,
    config_snapshot: "EscalationAgent_config_v1",
    created_at: now,
    updated_at: now,
  },
  {
    id: "eligibility-1",
    tree_id: "tree-1",
    name: "EligibilityCheck",
    role: "specialist",
    model: "gemini-2.5-flash",
    instruction: "Checks refund eligibility.",
    description: "Checks refund eligibility",
    tools: ["lookup_order"],
    parent_agent_id: "refund-1",
    score: 84,
    score_before: 52,
    is_shared: false,
    library_id: null,
    config_snapshot: "EligibilityCheck_config_v1",
    created_at: now,
    updated_at: now,
  },
  {
    id: "execution-1",
    tree_id: "tree-1",
    name: "RefundExecution",
    role: "specialist",
    model: "gemini-2.5-flash",
    instruction: "Executes approved refunds.",
    description: "Executes approved refunds",
    tools: ["issue_refund"],
    parent_agent_id: "refund-1",
    score: 80,
    score_before: 50,
    is_shared: false,
    library_id: null,
    config_snapshot: "RefundExecution_config_v1",
    created_at: now,
    updated_at: now,
  },
];

/* ── Agent Tree ── */
export const mockTree: AgentTree = {
  id: "tree-1",
  name: "Customer Support",
  description:
    "Multi-agent customer support tree handling billing, refunds, tech support, and escalations.",
  owner: "team-cx",
  agents: mockAgents,
  score: 87,
  score_before: 62,
  status: "idle",
  created_at: now,
  updated_at: now,
};

export const mockTrees: AgentTree[] = [
  mockTree,
  {
    id: "tree-2",
    name: "Sales Qualification v2",
    description: "Lead qualification and routing pipeline with intent scoring and handoff to sales reps.",
    owner: "team-sales",
    agents: [],
    agent_count: 5,
    score: 79,
    score_before: 71,
    status: "training",
    created_at: now,
    updated_at: now,
  },
  {
    id: "tree-3",
    name: "Onboarding Assistant v1",
    description: "New user onboarding flow with guided setup, feature tours, and activation tracking.",
    owner: "team-growth",
    agents: [],
    agent_count: 4,
    score: 73,
    score_before: 65,
    status: "idle",
    created_at: now,
    updated_at: now,
  },
];

/* ── Experiments ── */
export const mockExperiments: Experiment[] = [
  {
    id: "exp-1",
    session_id: "sess-1",
    tree_id: "tree-1",
    wave: 1,
    level: "L1",
    target_agent_id: "billing-1",
    target_agent_name: "BillingAgent",
    hypothesis: "Refined prompt with explicit invoice lookup instructions improves billing accuracy",
    rationale: "Analysis shows BillingAgent frequently fails to look up invoices before responding, leading to generic answers.",
    config_diff: {
      instruction: {
        before: "Handle billing inquiries...",
        after: "Handle billing inquiries. ALWAYS look up the customer's invoice before responding...",
      },
    },
    score_before: 58,
    score_after: 79,
    per_agent_scores: {
      "BillingAgent": { before: 58, after: 79 },
      "CustomerSupportOrchestrator": { before: 62, after: 64 },
      "RefundAgent": { before: 55, after: 56 },
    },
    per_dimension_scores: {
      trajectory: { before: 52, after: 82 },
      response: { before: 60, after: 78 },
      safety: { before: 90, after: 91 },
      efficiency: { before: 70, after: 68 },
      task_completion: { before: 75, after: 72 },
    },
    status: "kept",
    blast_radius: ["BillingAgent", "CustomerSupportOrchestrator"],
    cross_tree_results: [],
    impact_points: 8.2,
    summary: "Billing accuracy dramatically improved with explicit invoice lookup requirement.",
    created_at: now,
  },
  {
    id: "exp-2",
    session_id: "sess-1",
    tree_id: "tree-1",
    wave: 1,
    level: "L2",
    target_agent_id: "tech-1",
    target_agent_name: "TechSupportAgent",
    hypothesis: "Adding diagnostic tool chain improves first-contact resolution",
    rationale: "TechSupport resolves only 45% of issues on first contact. Adding structured diagnostic flow should help.",
    config_diff: {
      tools: {
        before: ["search_kb", "reset_account"],
        after: ["search_kb", "reset_account", "run_test", "auto_fix"],
      },
    },
    score_before: 67,
    score_after: 84,
    per_agent_scores: {
      "TechSupportAgent": { before: 67, after: 84 },
      "CustomerSupportOrchestrator": { before: 64, after: 66 },
    },
    per_dimension_scores: {
      trajectory: { before: 62, after: 86 },
      response: { before: 70, after: 88 },
      safety: { before: 88, after: 89 },
      efficiency: { before: 65, after: 60 },
      task_completion: { before: 80, after: 74 },
    },
    status: "kept",
    blast_radius: ["TechSupportAgent"],
    cross_tree_results: [],
    impact_points: 7.5,
    summary: "First-contact resolution improved with diagnostic chain.",
    created_at: now,
  },
  {
    id: "exp-3",
    session_id: "sess-1",
    tree_id: "tree-1",
    wave: 2,
    level: "L3",
    target_agent_id: "orch-1",
    target_agent_name: "CustomerSupportOrchestrator",
    hypothesis: "Intent classifier with confidence thresholds reduces misrouting",
    rationale: "20% of conversations are routed to the wrong specialist. Adding confidence-based fallback should improve.",
    config_diff: {
      routing: {
        before: { strategy: "keyword" },
        after: { strategy: "classifier", confidence_threshold: 0.85, fallback: "ask_clarification" },
      },
    },
    score_before: 64,
    score_after: 88,
    per_agent_scores: {
      "CustomerSupportOrchestrator": { before: 64, after: 88 },
      "BillingAgent": { before: 79, after: 82 },
      "TechSupportAgent": { before: 84, after: 87 },
      "RefundAgent": { before: 56, after: 60 },
      "EscalationAgent": { before: 60, after: 72 },
    },
    per_dimension_scores: {
      trajectory: { before: 58, after: 90 },
      response: { before: 66, after: 85 },
      safety: { before: 92, after: 93 },
      efficiency: { before: 72, after: 70 },
      task_completion: { before: 78, after: 76 },
    },
    status: "kept",
    blast_radius: ["CustomerSupportOrchestrator", "BillingAgent", "TechSupportAgent", "RefundAgent", "EscalationAgent"],
    cross_tree_results: [],
    impact_points: 9.8,
    summary: "Routing confusion reduced sharply with classifier + confidence threshold.",
    created_at: now,
  },
  {
    id: "exp-4",
    session_id: "sess-1",
    tree_id: "tree-1",
    wave: 2,
    level: "L1",
    target_agent_id: "refund-1",
    target_agent_name: "RefundAgent",
    hypothesis: "Adding eligibility check enforcement to refund prompt",
    rationale: "RefundAgent sometimes processes refunds without checking eligibility first.",
    config_diff: {
      instruction: {
        before: "Process refund requests...",
        after: "Process refund requests. MUST check eligibility before processing any refund...",
      },
    },
    score_before: 56,
    score_after: 78,
    per_agent_scores: {
      "RefundAgent": { before: 56, after: 78 },
    },
    per_dimension_scores: {
      trajectory: { before: 48, after: 80 },
      response: { before: 62, after: 76 },
      safety: { before: 70, after: 92 },
      efficiency: { before: 78, after: 76 },
      task_completion: { before: 82, after: 80 },
    },
    status: "kept",
    blast_radius: ["RefundAgent"],
    cross_tree_results: [],
    impact_points: 8.6,
    summary: "Eligibility compliance improved and refund success rate increased.",
    created_at: now,
  },
  {
    id: "exp-5",
    session_id: "sess-1",
    tree_id: "tree-1",
    wave: 3,
    level: "L4",
    target_agent_id: "auth-1",
    target_agent_name: "AuthAgent",
    hypothesis: "Shared auth agent library update with stricter MFA flow",
    rationale: "AuthAgent shared across trees. Stricter MFA improves security scores across all consumers.",
    config_diff: {
      mfa: {
        before: { required: false },
        after: { required: true, methods: ["totp", "sms", "email"] },
      },
    },
    score_before: 74,
    score_after: 91,
    per_agent_scores: {
      "AuthAgent": { before: 74, after: 91 },
      "CustomerSupportOrchestrator": { before: 88, after: 88 },
    },
    per_dimension_scores: {
      trajectory: { before: 72, after: 90 },
      response: { before: 70, after: 82 },
      safety: { before: 78, after: 96 },
      efficiency: { before: 80, after: 76 },
      task_completion: { before: 85, after: 83 },
    },
    status: "kept",
    blast_radius: ["AuthAgent"],
    cross_tree_results: [
      { tree_id: "tree-2", tree_name: "Sales Qualification v2", score_before: 71, score_after: 73, status: "pass" },
      { tree_id: "tree-3", tree_name: "Onboarding Assistant v1", score_before: 65, score_after: 66, status: "pass" },
    ],
    impact_points: 6.8,
    summary: "Auth security improved across all consuming trees without regressions.",
    created_at: now,
  },
  {
    id: "exp-6",
    session_id: "sess-1",
    tree_id: "tree-1",
    wave: 3,
    level: "L2",
    target_agent_id: "esc-1",
    target_agent_name: "EscalationAgent",
    hypothesis: "Priority scoring for escalation triage",
    rationale: "EscalationAgent treats all escalations equally. Adding priority scoring should improve response times.",
    config_diff: {
      tools: {
        before: ["escalate_to_human"],
        after: ["escalate_to_human", "score_priority", "auto_triage"],
      },
    },
    score_before: 60,
    score_after: 52,
    per_agent_scores: {
      "EscalationAgent": { before: 60, after: 52 },
    },
    per_dimension_scores: {
      trajectory: { before: 58, after: 50 },
      response: { before: 62, after: 54 },
      safety: { before: 85, after: 82 },
      efficiency: { before: 55, after: 48 },
      task_completion: { before: 70, after: 65 },
    },
    status: "reverted",
    blast_radius: ["EscalationAgent"],
    cross_tree_results: [],
    impact_points: -3.2,
    summary: "Priority scoring degraded triage quality. Reverted.",
    created_at: now,
  },
];

/* ── Waves ── */
export const mockWaves: WaveData[] = [
  {
    wave: 1,
    experiments: mockExperiments.filter((e) => e.wave === 1),
    status: "complete",
    started_at: now,
    completed_at: now,
  },
  {
    wave: 2,
    experiments: mockExperiments.filter((e) => e.wave === 2),
    status: "complete",
    started_at: now,
    completed_at: now,
  },
  {
    wave: 3,
    experiments: mockExperiments.filter((e) => e.wave === 3),
    status: "complete",
    started_at: now,
    completed_at: now,
  },
];

/* ── Training Session ── */
export const mockSession: TrainingSession = {
  id: "sess-1",
  tree_id: "tree-1",
  tree_name: "Customer Support",
  status: "complete",
  current_wave: 3,
  total_waves: 3,
  waves: mockWaves,
  score_start: 62,
  score_current: 87,
  scope: ["L1", "L2", "L3", "L4"],
  research_memory: {
    id: "rm-1",
    session_id: "sess-1",
    entries: [
      { timestamp: now, type: "observation", content: "BillingAgent has lowest score (58%) — primary bottleneck.", agent_id: "billing-1", experiment_id: null },
      { timestamp: now, type: "hypothesis", content: "Billing accuracy will improve with explicit invoice lookup instructions.", agent_id: "billing-1", experiment_id: "exp-1" },
      { timestamp: now, type: "result", content: "BillingAgent score improved 58% → 79% (+21pp). Keeping change.", agent_id: "billing-1", experiment_id: "exp-1" },
      { timestamp: now, type: "observation", content: "TechSupportAgent resolves only 45% on first contact.", agent_id: "tech-1", experiment_id: null },
      { timestamp: now, type: "result", content: "TechSupport improved 67% → 84% with diagnostic chain. Keeping.", agent_id: "tech-1", experiment_id: "exp-2" },
      { timestamp: now, type: "decision", content: "Moving to L3 routing optimization — 20% misrouting rate detected.", agent_id: "orch-1", experiment_id: null },
      { timestamp: now, type: "result", content: "Orchestrator routing improved 64% → 88%. Major win.", agent_id: "orch-1", experiment_id: "exp-3" },
      { timestamp: now, type: "result", content: "EscalationAgent priority scoring regressed 60% → 52%. Reverting.", agent_id: "esc-1", experiment_id: "exp-6" },
      { timestamp: now, type: "decision", content: "Wave 3 complete. Overall tree score: 62% → 87% (+25pp). Training complete.", agent_id: null, experiment_id: null },
    ],
  },
  created_at: now,
  updated_at: now,
};

/* ── Routing Data ── */
export const mockRoutingData: RoutingData = {
  paths: [
    {
      intent: "billing_inquiry",
      before: [
        { agent: "BillingAgent", correct: true, count: 62 },
        { agent: "TechSupportAgent", correct: false, count: 18 },
        { agent: "RefundAgent", correct: false, count: 12 },
        { agent: "EscalationAgent", correct: false, count: 8 },
      ],
      after: [
        { agent: "BillingAgent", correct: true, count: 91 },
        { agent: "TechSupportAgent", correct: false, count: 4 },
        { agent: "RefundAgent", correct: false, count: 3 },
        { agent: "EscalationAgent", correct: false, count: 2 },
      ],
      accuracy_before: 62,
      accuracy_after: 91,
    },
    {
      intent: "refund_request",
      before: [
        { agent: "RefundAgent", correct: true, count: 55 },
        { agent: "BillingAgent", correct: false, count: 30 },
        { agent: "EscalationAgent", correct: false, count: 15 },
      ],
      after: [
        { agent: "RefundAgent", correct: true, count: 88 },
        { agent: "BillingAgent", correct: false, count: 8 },
        { agent: "EscalationAgent", correct: false, count: 4 },
      ],
      accuracy_before: 55,
      accuracy_after: 88,
    },
    {
      intent: "tech_support",
      before: [
        { agent: "TechSupportAgent", correct: true, count: 70 },
        { agent: "BillingAgent", correct: false, count: 15 },
        { agent: "EscalationAgent", correct: false, count: 15 },
      ],
      after: [
        { agent: "TechSupportAgent", correct: true, count: 93 },
        { agent: "BillingAgent", correct: false, count: 3 },
        { agent: "EscalationAgent", correct: false, count: 4 },
      ],
      accuracy_before: 70,
      accuracy_after: 93,
    },
    {
      intent: "account_auth",
      before: [
        { agent: "AuthAgent", correct: true, count: 72 },
        { agent: "CustomerSupportOrchestrator", correct: false, count: 18 },
        { agent: "TechSupportAgent", correct: false, count: 10 },
      ],
      after: [
        { agent: "AuthAgent", correct: true, count: 94 },
        { agent: "CustomerSupportOrchestrator", correct: false, count: 4 },
        { agent: "TechSupportAgent", correct: false, count: 2 },
      ],
      accuracy_before: 72,
      accuracy_after: 94,
    },
  ],
};

/* ── Briefing Data ── */
export const mockBriefingData: BriefingData = {
  tree: mockTree,
  improvement: 25,
  score_start: 62,
  score_end: 87,
  agent_stats: [
    { agent_id: "orch-1", agent_name: "CustomerSupportOrchestrator", role: "orchestrator", score_before: 62, score_after: 88, delta: 26, experiments_applied: 1 },
    { agent_id: "auth-1", agent_name: "AuthAgent", role: "shared", score_before: 74, score_after: 91, delta: 17, experiments_applied: 1 },
    { agent_id: "billing-1", agent_name: "BillingAgent", role: "specialist", score_before: 58, score_after: 85, delta: 27, experiments_applied: 1 },
    { agent_id: "refund-1", agent_name: "RefundAgent", role: "specialist", score_before: 55, score_after: 82, delta: 27, experiments_applied: 1 },
    { agent_id: "tech-1", agent_name: "TechSupportAgent", role: "specialist", score_before: 67, score_after: 90, delta: 23, experiments_applied: 1 },
    { agent_id: "esc-1", agent_name: "EscalationAgent", role: "specialist", score_before: 60, score_after: 78, delta: 18, experiments_applied: 0 },
    { agent_id: "eligibility-1", agent_name: "EligibilityCheck", role: "specialist", score_before: 52, score_after: 84, delta: 32, experiments_applied: 1 },
    { agent_id: "execution-1", agent_name: "RefundExecution", role: "specialist", score_before: 50, score_after: 80, delta: 30, experiments_applied: 1 },
  ],
  progress: [
    { wave: 0, score: 62, timestamp: now },
    { wave: 1, score: 72, timestamp: now },
    { wave: 2, score: 81, timestamp: now },
    { wave: 3, score: 87, timestamp: now },
  ],
  routing: mockRoutingData,
  top_changes: mockExperiments.filter((e) => e.status === "kept").sort((a, b) => (b.score_after - b.score_before) - (a.score_after - a.score_before)),
  cross_tree_summary: [
    { tree_id: "tree-2", tree_name: "Sales Qualification v2", shared_agent: "AuthAgent", validation_status: "pass", score_delta: 2 },
    { tree_id: "tree-3", tree_name: "Onboarding Assistant v1", shared_agent: "AuthAgent", validation_status: "pass", score_delta: 1 },
  ],
  session: mockSession,
};

/* ── Diagnostic Report ── */
export const mockDiagnostics: DiagnosticReport = {
  tree_id: "tree-1",
  agents: [
    {
      agent_id: "orch-1",
      agent_name: "CustomerSupportOrchestrator",
      role: "orchestrator",
      score: 88,
      score_before: 62,
      dimensions: { trajectory: 90, response: 85, safety: 93, efficiency: 70, task_completion: 76 },
      issues: [],
    },
    {
      agent_id: "auth-1",
      agent_name: "AuthAgent",
      role: "shared",
      score: 91,
      score_before: 74,
      dimensions: { trajectory: 90, response: 82, safety: 96, efficiency: 76, task_completion: 83 },
      issues: [],
    },
    {
      agent_id: "billing-1",
      agent_name: "BillingAgent",
      role: "specialist",
      score: 85,
      score_before: 58,
      dimensions: { trajectory: 82, response: 78, safety: 91, efficiency: 68, task_completion: 72 },
      issues: ["Latency above target on complex queries"],
    },
    {
      agent_id: "refund-1",
      agent_name: "RefundAgent",
      role: "specialist",
      score: 82,
      score_before: 55,
      dimensions: { trajectory: 80, response: 76, safety: 92, efficiency: 76, task_completion: 80 },
      issues: [],
    },
    {
      agent_id: "tech-1",
      agent_name: "TechSupportAgent",
      role: "specialist",
      score: 90,
      score_before: 67,
      dimensions: { trajectory: 86, response: 88, safety: 89, efficiency: 60, task_completion: 74 },
      issues: ["Latency spike when running diagnostic chain"],
    },
    {
      agent_id: "esc-1",
      agent_name: "EscalationAgent",
      role: "specialist",
      score: 78,
      score_before: 60,
      dimensions: { trajectory: 72, response: 74, safety: 88, efficiency: 65, task_completion: 82 },
      issues: ["Below target accuracy", "Slow triage on priority classification"],
    },
    {
      agent_id: "eligibility-1",
      agent_name: "EligibilityCheck",
      role: "specialist",
      score: 84,
      score_before: 52,
      dimensions: { trajectory: 86, response: 80, safety: 94, efficiency: 72, task_completion: 78 },
      issues: [],
    },
    {
      agent_id: "execution-1",
      agent_name: "RefundExecution",
      role: "specialist",
      score: 80,
      score_before: 50,
      dimensions: { trajectory: 78, response: 76, safety: 90, efficiency: 70, task_completion: 80 },
      issues: ["Confirmation messages could be more detailed"],
    },
  ],
  opportunities: [
    {
      id: "opp-1",
      agent_id: "esc-1",
      agent_name: "EscalationAgent",
      description: "Escalation accuracy below 75% — needs refined triage logic",
      priority: "critical",
      level: "L2",
      estimated_impact: 12,
    },
    {
      id: "opp-2",
      agent_id: "billing-1",
      agent_name: "BillingAgent",
      description: "Complex billing queries have 2.5s average latency — optimize tool chain",
      priority: "high",
      level: "L2",
      estimated_impact: 8,
    },
    {
      id: "opp-3",
      agent_id: "tech-1",
      agent_name: "TechSupportAgent",
      description: "Diagnostic chain causes latency spike — consider parallel execution",
      priority: "medium",
      level: "L2",
      estimated_impact: 5,
    },
    {
      id: "opp-4",
      agent_id: "refund-1",
      agent_name: "RefundAgent",
      description: "Refund helpfulness score lagging — improve explanation quality",
      priority: "medium",
      level: "L1",
      estimated_impact: 4,
    },
  ],
};

/* ── Deployment ── */
export const mockDeployment: Deployment = {
  id: "deploy-1",
  session_id: "sess-1",
  status: "active",
  canary_percent: 10,
  canary_score: 89,
  target_score: 85,
  approved_by: "andrew@autoagent.dev",
  scope: "full_tree",
  mode: "canary",
  target_agent_ids: [],
  deployed_at: now,
};
